accounts/urls.py
from django.urls import path

app_name = 'accounts'

# accounts views
from accounts.views import SignupView
from accounts.views import UserLogout
from accounts.views import UserLoginView


urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', UserLogout.as_view(), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

# Static Files settings import 
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.views import serve
from django.conf import settings

# Apps Urls
from accounts import urls as accounts_urls
from authority import urls as authority_urls
from customer import urls as customer_urls
from home import urls as home_urls
from products import urls as products_urls
from payment import urls as payment_urls
from deleveryman import urls as deleveryman_urls
from reports import urls as report_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(accounts_urls)),
    path('', include(authority_urls)),
    path('', include(customer_urls)),
    path('', include(home_urls)),
    path('', include(products_urls)),
    path('', include(payment_urls)),
    path('', include(deleveryman_urls)),
    path('', include(report_urls)),

]

# Serve Static Files
# for serve static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, view=serve)

customer/urls.py
from django.urls import path


app_name = 'customer'

#Import Views
from customer.views import CustomerHomeView
from customer.views import MyOrderListView
from customer.views import MyConfirmedOrderListView
from customer.views import AddProfileInfo

urlpatterns = [

path('customer/', CustomerHomeView.as_view(), name='customer'),
path('my_pending_order/', MyOrderListView.as_view(), name='my_pending_list'),
path('my_confirmed_order/', MyConfirmedOrderListView.as_view(), name='my_confirmed_list'),
path('edit-profile/<int:pk>/', AddProfileInfo.as_view(),name="edit_profile")
    
]

home/urls.py
from django.urls import path

app_name='home'

# Home Views
from home.views import home
from home.views import manage_chart

urlpatterns = [
    path("", home.Home.as_view(), name="home"),
    path("home/", home.Home.as_view(), name="home"),
    path("all-product", home.AllProductView.as_view(), name="all_products"),
    path("product-details/<int:pk>/", home.ProductsDetailsView.as_view(), name="product_details"),
    
]


# manage order
urlpatterns += [
    path('add-to-cart/<int:pk>/', manage_chart.add_to_cart, name='add_to_cart'),
    path('cart-details/', manage_chart.ChartProductListView.as_view(), name='cart_details'),
    path('remove-from_cart/<int:pk>/', manage_chart.remove_form_cart, name='remove_form_cart'),
    path('increase-from-cart/<int:pk>/',manage_chart.increase_cart_item, name='increase_cart'),
    path('decrease-from-cart/<int:pk>/',manage_chart.decrease_cart_item, name='decrease_cart'),
    path('my-order/', manage_chart.MyOrderListView.as_view(),name="my_order"),
]

home/models.py
from django.db import models

# Create your models here.

home/views/home.py
from django.shortcuts import redirect


# Generc Classes
from django.views.generic import TemplateView
from django.views.generic import ListView
from django.views.generic import DetailView

# Import Models
from products.models import Product



# Create your views here.
class Home(TemplateView):
    template_name = 'home/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Home" 
        context["recent_product"] = Product.objects.filter(is_active=True).order_by('-id')[:8] 
        context["featured_product"] = Product.objects.filter(is_active=True, product_type='featured').order_by('-id')[:10] 
        
        return context

class AllProductView(ListView):
    queryset = Product.objects.all()
    template_name = 'home/all_products.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "All Products" 
        context["products"] = self.queryset
        return context

class ProductsDetailsView(DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'home/products_details.html'

    def get_context_data(self, **kwargs):
        product_pk = self.kwargs['pk']
        product = Product.objects.get(id=product_pk)
        sub_category = product.sub_catagory_1
        context = super().get_context_data(**kwargs)
        context["title"] = "Product Details"
        context["related_products"] = Product.objects.filter(sub_catagory_1=sub_category)[:4]
        return context

    

home/views/manage_chart.py
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.db.models import F, Sum

# Generic Classes
from django.views.generic import TemplateView
from django.views.generic import ListView

# Permission 
from django.contrib.auth.mixins import LoginRequiredMixin

# Models
from products.models import Cart
from products.models import Order
from products.models import Product
from accounts.models import User
from authority.models import ShippingCharge


@login_required
def add_to_cart(request, pk):
    # item = get_object_or_404(Product, id=pk)
    item = Product.objects.get(id=pk)

    order_item = Cart.objects.get_or_create(items=item, user=request.user,purchased=False)
    order_qs = Order.objects.filter(user = request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]
        
        if order.orderitems.filter(items=item).exists():
            order_item[0].quentity +=1
            order_item[0].save()
            return redirect('home:home')
        else:
            order.orderitems.add(order_item[0])
            return redirect('home:home')
    else:
        order = Order(user=request.user)
        order.save()
        order.orderitems.add(order_item[0])
        return redirect('home:home')

class ChartProductListView(LoginRequiredMixin, TemplateView):

    template_name = 'home/cart_details.html'

    def get_context_data(self, **kwargs):
        chart_items = Cart.objects.filter(user =self.request.user, purchased = False)
        shipping_charge = ShippingCharge.objects.latest('id')
        total_price = Cart.objects.filter(user=self.request.user, purchased=False).annotate(item_total=F('quentity') * F('items__product_price')).aggregate(total_price=Sum('item_total'))['total_price'] or 0
        discount = 0
        for cart_item in chart_items:
            discount += float(cart_item.get_discount_amount())  # Assuming discount_percentage is defined
        context = super().get_context_data(**kwargs)

        context["title"] = "Cart Page"
        context["products"] = Product.objects.filter(is_active=True).order_by('-id')[:10]
        context["chart_items"] =  chart_items
        context["total_items"] = Cart.objects.filter(user =self.request.user, purchased = False).count()
        context["total_price"] =Cart.objects.filter(user=self.request.user, purchased=False).annotate(item_total=F('quentity') * F('items__product_price')).aggregate(total_price=Sum('item_total'))['total_price'] or 0
        context["shipping_charge"] = shipping_charge
        context["discount"] = discount
        context["shipping_total"] = ((shipping_charge.shipping_charge+total_price)-discount)
        return context

@login_required
def remove_form_cart(request, pk):
    item = get_object_or_404(Product, id = pk)
    order_qs = Order.objects.filter(user = request.user, ordered = False)

    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(items=item).exists():
            order_item = Cart.objects.filter(items=item, user= request.user, purchased=False )[0]
            order_item.items.stock += order_item.quentity
            order_item.items.save()
            order.orderitems.remove(order_item)
            order_item.delete()
            return redirect('home:cart_details')
        else:
            return redirect('home:home')
    else:
        return redirect('home:home')

@login_required
def increase_cart_item(request, pk):
    item = get_object_or_404(Product, id = pk)
    order_qs = Order.objects.filter(user = request.user, ordered = False)

    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(items=item).exists():
            order_item = Cart.objects.filter(items=item, user= request.user, purchased=False )[0]

            if order_item.quentity >= 1:
                order_item.quentity +=1
                order_item.save()
            return redirect('home:cart_details')
        else:
            return redirect('home:home')
    else:
        return redirect('home:home')
    
@login_required
def decrease_cart_item(request, pk):
    item = get_object_or_404(Product, id = pk)
    order_qs = Order.objects.filter(user = request.user, ordered = False)

    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(items=item).exists():
            order_item = Cart.objects.filter(items=item, user= request.user, purchased=False )[0]

            if order_item.quentity > 1:
                order_item.quentity -=1
                order_item.save()
                return redirect('home:cart_details')
            else:
                order.orderitems.remove(order_item)
                order_item.delete()
                return redirect('home:cart_details')
        else:
            return redirect('home:home')
    else:
        return redirect('home:home')

class MyOrderListView(LoginRequiredMixin, ListView):
    model = Order
    context_object_name = 'orders'
    template_name = 'home/my_order.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user, ordered=True).order_by('id')[:10]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "My order"
        context["shipping_charge"] = ShippingCharge.objects.latest('id')
        return context

home/templates/home_base/heor.html
{% load static %}
<div class="row">
    <div class="col-2">
        <h1>Make Your Life <br> Easy With Us</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.<br> Magnam, quo culpa temporibus maxime accusantium dignissimos adipisci eligendi doloremque illo quaerat assumenda voluptas laborum sunt. Alias voluptatibus dolorum dolor dolores voluptates?</p>
        <a href="#" class="btn"> Explore Now &#8594;</a>

    </div>
    <div class="col-2">
        <img src="{% static 'home/images/hero.jpg' %}" alt="">
    </div>
</div>

home/templates/home_base/home_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %}{% endblock title %} </title>
    <link rel="stylesheet" href="{% static 'home/css/homes.css' %}">

    <!-- ----- font-asesome------------- -->
     <!-- font-aswome cdn -->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
     <script src="https://kit.fontawesome.com/ddee993d4e.js" crossorigin="anonymous"></script>
</head>
<body>
    <!-- nav-bar code start -->
    <div class="header">
        <div class="container">
            <div class="navbar">
                <div class="logo">
                    <img src="{% static 'home/images/logo.png' %}" alt="" width="125px">
                </div>
                <nav>
                    <ul id="MenuItems">
                        <li><a href="{% url 'home:home' %}">Home</a></li>
                        <li><a href="{% url 'home:all_products' %}">Products</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'customer:customer' %}">profile</a></li>
                            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                        {% else %}
                            <li><a href="{% url 'accounts:login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                    {% if user.is_authenticated %}
                        <a href="{% url 'home:cart_details' %}"><img src="{% static 'home/images/cart.png' %}" alt="" width="30px" height="30px">
                            {% if chart_item_quetity %}
                                ({{chart_item_quetity}})
                            {% endif %}
                        </a>   
                    {% endif %}
                    <img src="{% static 'home/images/menu.png' %}" class="menu-icon" onclick="menutoggle()">
                </nav>
            </div>
            {% block heor %}
               
            {% endblock heor %}
        </div>
    </div>

    {% block body %}

        
    {% endblock body %}


<div class="footer">
    <div class="container">

        <div class="row">
            <div class="footer-col-1">
                <h3>Download Our App</h3>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit.</p>
            </div>
            <div class="footer-col-2">
                <img src="{% static 'home/images/logo-white.png' %}" alt="">
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit.</p>
            </div>
            <div class="footer-col-3">
                <h3>Useful Links</h3>
                <ul>
                    <li>Coupons</li>
                    <li>Blog Post</li>
                    <li>Return Policy</li>
                    <li>Join Affiliate</li>
                </ul>
            </div>
            <div class="footer-col-4">
                <h3>Follow Us</h3>
                <ul>
                    <li>Facebook</li>
                    <li>Twitter</li>
                    <li>Instagram</li>
                    <li>YouTube</li>
                </ul>
            </div>
        </div>
        <hr>
        <p class="copyright">Copyright-2023 RED-STORE </p>
    </div>
</div>

<!-- js for toggle menu -->
<script>
    var MenuItems = document.getElementById("MenuItems");

    function menutoggle(){
        if (MenuItems.style.maxHeight == "0px")
        {
            MenuItems.style.maxHeight = "200px";
        }
        else{
            MenuItems.style.maxHeight = "0px";
        }
    }
</script>
    
</body>
</html>