accounts/urls.py
from django.urls import path

app_name = 'accounts'

# accounts views
from accounts.views import SignupView
from accounts.views import UserLogout
from accounts.views import UserLoginView


urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', UserLogout.as_view(), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

# Static Files settings import 
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.views import serve
from django.conf import settings

# Apps Urls
from accounts import urls as accounts_urls
from authority import urls as authority_urls
from customer import urls as customer_urls
from home import urls as home_urls
from products import urls as products_urls
from payment import urls as payment_urls
from deleveryman import urls as deleveryman_urls
from reports import urls as report_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(accounts_urls)),
    path('', include(authority_urls)),
    path('', include(customer_urls)),
    path('', include(home_urls)),
    path('', include(products_urls)),
    path('', include(payment_urls)),
    path('', include(deleveryman_urls)),
    path('', include(report_urls)),

]

# Serve Static Files
# for serve static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, view=serve)

home/urls.py
from django.urls import path

app_name='home'

# Home Views
from home.views import home
from home.views import manage_chart

urlpatterns = [
    path("", home.Home.as_view(), name="home"),
    path("home/", home.Home.as_view(), name="home"),
    path("all-product", home.AllProductView.as_view(), name="all_products"),
    path("product-details/<int:pk>/", home.ProductsDetailsView.as_view(), name="product_details"),
    
]


# manage order
urlpatterns += [
    path('add-to-cart/<int:pk>/', manage_chart.add_to_cart, name='add_to_cart'),
    path('cart-details/', manage_chart.ChartProductListView.as_view(), name='cart_details'),
    path('remove-from_cart/<int:pk>/', manage_chart.remove_form_cart, name='remove_form_cart'),
    path('increase-from-cart/<int:pk>/',manage_chart.increase_cart_item, name='increase_cart'),
    path('decrease-from-cart/<int:pk>/',manage_chart.decrease_cart_item, name='decrease_cart'),
    path('my-order/', manage_chart.MyOrderListView.as_view(),name="my_order"),
]

payment/urls.py
from django.urls import path

app_name = 'payment'

from payment.views import check_out
from payment.views import payment
from payment.views import complete_payment
from payment.views import purchase
from payment.views import cashon_purchase

urlpatterns = [
    path('checkout/', check_out, name='checkout'),
    path('payment/', payment, name='payment'),
    path('payment-success/', complete_payment, name='payment_success'),
    path('purchase/<val_id>/<tran_id>/', purchase, name='purchase'),
    path('cash-on-purchase/', cashon_purchase, name='cash_on_purchase'),
]

home/models.py
from django.db import models

# Create your models here.

home/views/home.py
from django.shortcuts import redirect


# Generc Classes
from django.views.generic import TemplateView
from django.views.generic import ListView
from django.views.generic import DetailView

# Import Models
from products.models import Product



# Create your views here.
class Home(TemplateView):
    template_name = 'home/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Home" 
        context["recent_product"] = Product.objects.filter(is_active=True).order_by('-id')[:8] 
        context["featured_product"] = Product.objects.filter(is_active=True, product_type='featured').order_by('-id')[:10] 
        
        return context

class AllProductView(ListView):
    queryset = Product.objects.all()
    template_name = 'home/all_products.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "All Products" 
        context["products"] = self.queryset
        return context

class ProductsDetailsView(DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'home/products_details.html'

    def get_context_data(self, **kwargs):
        product_pk = self.kwargs['pk']
        product = Product.objects.get(id=product_pk)
        sub_category = product.sub_catagory_1
        context = super().get_context_data(**kwargs)
        context["title"] = "Product Details"
        context["related_products"] = Product.objects.filter(sub_catagory_1=sub_category)[:4]
        return context

    

home/views/manage_chart.py
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.db.models import F, Sum

# Generic Classes
from django.views.generic import TemplateView
from django.views.generic import ListView

# Permission 
from django.contrib.auth.mixins import LoginRequiredMixin

# Models
from products.models import Cart
from products.models import Order
from products.models import Product
from accounts.models import User
from authority.models import ShippingCharge


@login_required
def add_to_cart(request, pk):
    # item = get_object_or_404(Product, id=pk)
    item = Product.objects.get(id=pk)

    order_item = Cart.objects.get_or_create(items=item, user=request.user,purchased=False)
    order_qs = Order.objects.filter(user = request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]
        
        if order.orderitems.filter(items=item).exists():
            order_item[0].quentity +=1
            order_item[0].save()
            return redirect('home:home')
        else:
            order.orderitems.add(order_item[0])
            return redirect('home:home')
    else:
        order = Order(user=request.user)
        order.save()
        order.orderitems.add(order_item[0])
        return redirect('home:home')

class ChartProductListView(LoginRequiredMixin, TemplateView):

    template_name = 'home/cart_details.html'

    def get_context_data(self, **kwargs):
        chart_items = Cart.objects.filter(user =self.request.user, purchased = False)
        shipping_charge = ShippingCharge.objects.latest('id')
        total_price = Cart.objects.filter(user=self.request.user, purchased=False).annotate(item_total=F('quentity') * F('items__product_price')).aggregate(total_price=Sum('item_total'))['total_price'] or 0
        discount = 0
        for cart_item in chart_items:
            discount += float(cart_item.get_discount_amount())  # Assuming discount_percentage is defined
        context = super().get_context_data(**kwargs)

        context["title"] = "Cart Page"
        context["products"] = Product.objects.filter(is_active=True).order_by('-id')[:10]
        context["chart_items"] =  chart_items
        context["total_items"] = Cart.objects.filter(user =self.request.user, purchased = False).count()
        context["total_price"] =Cart.objects.filter(user=self.request.user, purchased=False).annotate(item_total=F('quentity') * F('items__product_price')).aggregate(total_price=Sum('item_total'))['total_price'] or 0
        context["shipping_charge"] = shipping_charge
        context["discount"] = discount
        context["shipping_total"] = ((shipping_charge.shipping_charge+total_price)-discount)
        return context

@login_required
def remove_form_cart(request, pk):
    item = get_object_or_404(Product, id = pk)
    order_qs = Order.objects.filter(user = request.user, ordered = False)

    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(items=item).exists():
            order_item = Cart.objects.filter(items=item, user= request.user, purchased=False )[0]
            order_item.items.stock += order_item.quentity
            order_item.items.save()
            order.orderitems.remove(order_item)
            order_item.delete()
            return redirect('home:cart_details')
        else:
            return redirect('home:home')
    else:
        return redirect('home:home')

@login_required
def increase_cart_item(request, pk):
    item = get_object_or_404(Product, id = pk)
    order_qs = Order.objects.filter(user = request.user, ordered = False)

    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(items=item).exists():
            order_item = Cart.objects.filter(items=item, user= request.user, purchased=False )[0]

            if order_item.quentity >= 1:
                order_item.quentity +=1
                order_item.save()
            return redirect('home:cart_details')
        else:
            return redirect('home:home')
    else:
        return redirect('home:home')
    
@login_required
def decrease_cart_item(request, pk):
    item = get_object_or_404(Product, id = pk)
    order_qs = Order.objects.filter(user = request.user, ordered = False)

    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(items=item).exists():
            order_item = Cart.objects.filter(items=item, user= request.user, purchased=False )[0]

            if order_item.quentity > 1:
                order_item.quentity -=1
                order_item.save()
                return redirect('home:cart_details')
            else:
                order.orderitems.remove(order_item)
                order_item.delete()
                return redirect('home:cart_details')
        else:
            return redirect('home:home')
    else:
        return redirect('home:home')

class MyOrderListView(LoginRequiredMixin, ListView):
    model = Order
    context_object_name = 'orders'
    template_name = 'home/my_order.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user, ordered=True).order_by('id')[:10]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "My order"
        context["shipping_charge"] = ShippingCharge.objects.latest('id')
        return context

home/templates/home/all_products.html
{% extends 'home_base/home_base.html' %}
{% load static %}

{% block title %}{% endblock title %}

{% block body %}
    <div class="small-container">
        <h2 class="title">All Products</h2>
        <div class="row">
            {% if products %}
                {% for product in products %}
                    <a href="{% url 'home:product_details' product.id %}">
                        <div class="col-4">
                            <img src="{{product.main_image.url}}" alt="">
                            <h4> {{product.product_name}} ({{product.unit}}) </h4>
                            <div class="rating">
                                <i class="fa-solid fa-star"></i>
                                <i class="fa-solid fa-star"></i>
                                <i class="fa-solid fa-star"></i>
                                <i class="fa-solid fa-star"></i>
                                <i class="fa-regular fa-star"></i>
                            </div>
                            <p>$ {{product.product_price}} (-{{product.discount}}%) </p>
                            {% if product.stock != 0 %}
                                <a href="{% url 'home:add_to_cart' product.id %}" class="btn"> Add To Cart</a>
                            {% else %}
                                <h5> Stock Out </h5>
                            {% endif %}
                            
                        </div>
                    </a>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock body %}

home/templates/home/cart_details.html
{% extends 'home_base/home_base.html' %}
{% load static %}

{% block title %} {{title}} {% endblock title %}

{% block body %}
    <!-- ------------------------- Chart Items Details---------------------------- -->
    <div class="small-container cart-page">
        
        {% if chart_items %}
            <table>
                <tr>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Sub Total</th>
                </tr>
                {% for chart_item in chart_items %}
                    <tr>
                        <td>
                            <div class="cart-info">
                                <img src="{{chart_item.items.main_image.url}}" alt="">
                                <div>
                                    <p> {{chart_item.items.product_name}} </p>
                                    <small>Tk {{chart_item.items.product_price}}(-{{chart_item.items.discount}}%) </small>
                                    <br>
                                    <a href="{% url 'home:remove_form_cart' chart_item.items.id %}">Remove</a>
                                </div>
                            </div>
                        </td>
                        <td>
                            <a href="{% url 'home:increase_cart' chart_item.items.id %}" class="btn cart-btn"><i class="fa-solid fa-plus"></i></a>
                            <p class="input-quentity"> {{chart_item.quentity}} </p>
                            <a href="{% url 'home:decrease_cart' chart_item.items.id %}" class="btn cart-btn"><i class="fa-solid fa-minus"></i></a>
                        </td>
                        <td>Tk {{chart_item.get_total}} (-{{chart_item.get_discount_amount}}) </td>
                    </tr>
            {% endfor %}
            
        </table>

        {% endif %}
        {% if chart_items %}
                <div class="total-price">
                    <table>
                        <tr>
                            <td>Total Items</td>
                            <td> {{total_items}} </td>
                        </tr>
                        <tr>
                            <td>Sub Total(Whout Discoutn)</td>
                            <td> {{total_price}} /- </td>
                        </tr>
                        <tr>
                            <td>Discount</td>
                            <td> {{discount}} /- </td>
                        </tr>
                        <tr>
                            <td>Shipping Charge</td>
                            <td>{{shipping_charge.shipping_charge}}/-</td>
                        </tr>
                        <tr>
                            <td>Total</td>
                            <td> {{shipping_total}}/- </td>
                        </tr>
                    </table>
                    
                </div>
                <div class="total-price">
                    <a href="{% url 'payment:checkout' %}" class="btn"> Checkout </a>
                </div>
                

                {% else %}
                    <div class="small-container">
                        <h2 class="title">Chart Is Empty</h2>
                            <div class="row">
                                {% if products %}
                                {% for product in products %}
                                    <a href="{% url 'home:product_details' product.id %}">
                                        <div class="col-4">
                                            <img src="{{product.main_image.url}}" alt="">
                                            <h4> {{product.product_name}} ({{product.unit}}) </h4>
                                            <div class="rating">
                                                <i class="fa-solid fa-star"></i>
                                                <i class="fa-solid fa-star"></i>
                                                <i class="fa-solid fa-star"></i>
                                                <i class="fa-solid fa-star"></i>
                                                <i class="fa-regular fa-star"></i>
                                            </div>
                                            <p>$ {{product.product_price}} (-{{product.discount}}%) </p>
                                            {% if product.stock != 0 %}
                                                <a href="{% url 'home:add_to_cart' product.id %}" class="btn"> Add To Cart</a>
                                            {% else %}
                                                    <h5> Stock Out </h5>
                                            {% endif %}
                                        </div>
                                    </a>
                                {% endfor %}
                            {% endif %} 
                                
                            
                            </div>
                    </div> 
                
            {% endif %}
        </div>

        <div class="small-container">
            <h2 class="title">Suggested Product</h2>
                <div class="row">
                    {% if products %}
                    {% for product in products %}
                        <a href="{% url 'home:product_details' product.id %}">
                            <div class="col-4">
                                <img src="{{product.main_image.url}}" alt="">
                                <h4> {{product.product_name}} ({{product.unit}}) </h4>
                                <div class="rating">
                                    <i class="fa-solid fa-star"></i>
                                    <i class="fa-solid fa-star"></i>
                                    <i class="fa-solid fa-star"></i>
                                    <i class="fa-solid fa-star"></i>
                                    <i class="fa-regular fa-star"></i>
                                </div>
                                <p>$ {{product.product_price}} (-{{product.discount}}%) </p>
                                {% if product.stock != 0 %}
                                    <a href="{% url 'home:add_to_cart' product.id %}" class="btn"> Add To Cart</a>
                                {% else %}
                                        <h5> Stock Out </h5>
                                {% endif %}
                            </div>
                        </a>
                    {% endfor %}
                {% endif %} 
                    
                </div>
        </div>
         
{% endblock body %}


    
<h2 class="title">You Have No Product In your chart</h2>

<div class="row">
    {% if products %}
    {% for product in products %}
        <a href="{% url 'home:product_details' product.id %}">
            <div class="col-4">
                <img src="{{product.main_image.url}}" alt="">
                <h4> {{product.product_name}} ({{product.unit}}) </h4>
                <div class="rating">
                    <i class="fa-solid fa-star"></i>
                    <i class="fa-solid fa-star"></i>
                    <i class="fa-solid fa-star"></i>
                    <i class="fa-solid fa-star"></i>
                    <i class="fa-regular fa-star"></i>
                </div>
                <p>$ {{product.product_price}} (-{{product.discount}}%) </p>
                {% if product.stock != 0 %}
                    <a href="{% url 'home:add_to_cart' product.id %}" class="btn"> Add To Cart</a>
                {% else %}
                        <h5> Stock Out </h5>
                {% endif %}
            </div>
        </a>
    {% endfor %}
{% endif %} 

home/templates/home/index.html
{% extends 'home_base/home_base.html' %}
{% load static %}

{% block title %}{% endblock title %}


{% block body %}
{% block hero %}
    {% include "home_base/heor.html" %}
{% endblock hero %}


<!-- --------------featured product------------ -->
<div class="small-container">
    <h2 class="title">Featured Products</h2>
    <div class="row">
        {% if featured_product %}
                {% for product in featured_product %}
                <a href="{% url 'home:product_details' product.id %}">
                    <div class="col-4">
                        <img src="{{product.main_image.url}}" alt="">
                        <h4> {{product.product_name}} ({{product.unit}}) </h4>
                        <div class="rating">
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-regular fa-star"></i>
                        </div>
                        <p>$ {{product.product_price}} (-{{product.discount}}%) </p>
                        {% if product.stock != 0 %}
                            <a href="{% url 'home:add_to_cart' product.id %}" class="btn"> Add To Cart</a>
                        {% else %}
                            <h5> Stock Out </h5>
                        {% endif %}
                    </div>
                </a>
                
                {% endfor %} 
            {% endif %} 
    </div>
    <!-- -------------recent product --------- -->
    <h2 class="title">Recent Products</h2>
    
        <div class="row">
            {% if recent_product %}
            {% for product in recent_product %}
                <a href="{% url 'home:product_details' product.id %}">
                    <div class="col-4">
                        <img src="{{product.main_image.url}}" alt="">
                        <h4> {{product.product_name}} ({{product.unit}}) </h4>
                        <div class="rating">
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-regular fa-star"></i>
                        </div>
                        <p>$ {{product.product_price}} (-{{product.discount}}%) </p>
                        {% if product.stock != 0 %}
                                <a href="{% url 'home:add_to_cart' product.id %}" class="btn"> Add To Cart</a>
                            {% else %}
                                <h5> Stock Out </h5>
                        {% endif %}
                    </div>
                </a>
            {% endfor %}
        {% endif %} 
            
        
        </div>
</div> 


{% comment %} <!-- ------------- offer ---------- -->
<div class="offer">
<div class="small-container">
    <div class="row">
        <div class="col-2">
            <img class="offer-img" src="images/exclusive.png" alt="">
        </div>
        <div class="col-2">
            <p>Exclusively Available on Red Store</p>
            <h1>Smart Band 4</h1>
            <small>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut ab amet nisi totam soluta ea nobis, iure nam blanditiis maiores pariatur nihil quod aperiam dolores molestias, enim dignissimos. Fugiat, autem.</small>
            <a href="#" class="btn">Buy Now &#8594;</a>
        </div>
    </div>
</div>
</div> {% endcomment %}

<!-- -----------testimonial--------- -->
<div class="testimonial">
<div class="small-container">
    <div class="row">

        <div class="col-3">
            <i class="fa-solid fa-quote-left"></i>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis ratione at ipsum in, vero necessitatibus ad autem consequuntur, explicabo ab, adipisci labore aliquid facilis nihil aliquam repellat quae aperiam sit!</p>
            <div class="rating">
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-regular fa-star"></i>
            </div>
            <img src="{% static 'home/images/user-1.png' %}" alt="">
            <h3>Mark Atto</h3>
        </div>
        <div class="col-3">
            <i class="fa-solid fa-quote-left"></i>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis ratione at ipsum in, vero necessitatibus ad autem consequuntur, explicabo ab, adipisci labore aliquid facilis nihil aliquam repellat quae aperiam sit!</p>
            <div class="rating">
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-regular fa-star"></i>
            </div>
            <img src="{% static 'home/images/user-2.png' %}" alt="">
            <h3>Mark Atto</h3>
        </div>
        <div class="col-3">
            <i class="fa-solid fa-quote-left"></i>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis ratione at ipsum in, vero necessitatibus ad autem consequuntur, explicabo ab, adipisci labore aliquid facilis nihil aliquam repellat quae aperiam sit!</p>
            <div class="rating">
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-regular fa-star"></i>
            </div>
            <img src="{% static 'home/images/user-3.png' %}" alt="">
            <h3>Mark Atto</h3>
        </div>

    </div>
</div>
</div>

<!-- ------------------brands-------------- -->
<div class="brands">
<div class="small-container">
    <div class="row">
        <div class="col-5">
            <img src="{% static 'home/images/logo-godrej.png' %}" alt="">

        </div>
        <div class="col-5">
            <img src="{% static 'home/images/logo-oppo.png' %}" alt="">

        </div>
        <div class="col-5">
            <img src="{% static 'home/images/logo-coca-cola.png' %}" alt="">

        </div>
        <div class="col-5">
            <img src="{% static 'home/images/logo-paypal.png' %}" alt="">

        </div>
        <div class="col-5">
            <img src="{% static 'home/images/logo-philips.png' %}" alt="">

        </div>
    </div>
</div>
</div>
{% endblock body %}

home/templates/home/products_details.html
{% extends 'home_base/home_base.html' %}
{% load static %}

{% block title %} {{title}} {% endblock title %}

{% block body %}
<!-- --------------------- Single Product Details------------ -->
<div class="small-container single-product">
    <div class="row">
        <div class="col-2">
            <img src="{{product.main_image.url}}" alt="" width="100%" id="ProductImg">

            <div class="small-img-row">
                <div class="small-img-col">
                    <img src=" {{product.main_image.url}} " alt="" width="100%" class="small-img">
                    
                </div>
                <div class="small-img-col">
                    <img src=" {{product.image_1.url}} " alt="" width="100%" class="small-img">

                </div>
                <div class="small-img-col">
                    <img src=" {{product.image_2.url}} " alt="" width="100%" class="small-img">

                </div>
                <div class="small-img-col">
                    <img src=" {{product.image_3.url}} " alt="" width="100%" class="small-img">

                </div>
            </div>
        </div>
        <div class="col-2">
            <h1 > {{product.product_name}} ( {{product.unit}} )</h1>
            <h4> {{product.product_price}} (-{{product.discount}}%) TK </h4>
            {% if product.stock != 0 %}
                    <a href="{% url 'home:add_to_cart' product.id %}" class="btn"> Add To Cart</a>
                {% else %}
                    <h5> Stock Out </h5>
            {% endif %}

            <h3>Product Details <i class="fa fa-indent "></i></h3>
            <br>
            <p> {{product.description}} </p>
        </div>
    </div>
</div>

<!-- ---------title----------------- -->
<div class="small-container">
    <div class="row row-2">
        <h2 class="title">Related Products</h2>
        <p>View more</p>

    </div>
</div>

<div class="small-container">
    <div class="row">
        {% if related_products %}
            {% for product in related_products %}
                <a href="{% url 'home:product_details' product.id %}">
                    <div class="col-4">
                        <img src="{{product.main_image.url}}" alt="">
                        <h4> {{product.product_name}} ({{product.unit}}) </h4>
                        <div class="rating">
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-solid fa-star"></i>
                            <i class="fa-regular fa-star"></i>
                        </div>
                        <p>$ {{product.product_price}} (-{{product.discount}}%) </p>
                        {% if product.stock != 0 %}
                                <a href="{% url 'home:add_to_cart' product.id %}" class="btn"> Add To Cart</a>
                        {% else %}
                                <h5> Stock Out </h5>
                        {% endif %}
                    </div>
                </a>
            {% endfor %}
        {% endif %}
    </div>
</div>

<!-- ------------------js for product gallery----------- -->
<script>
    var ProductImg = document.getElementById("ProductImg");
    var SmallImg = document.getElementsByClassName("small-img");

    SmallImg[0].onclick = function(){
        ProductImg.src = SmallImg[0].src;
    }
    SmallImg[1].onclick = function(){
        ProductImg.src = SmallImg[1].src;
    }
    SmallImg[2].onclick = function(){
        ProductImg.src = SmallImg[2].src;
    }
    SmallImg[3].onclick = function(){
        ProductImg.src = SmallImg[3].src;
    }
</script>
{% endblock body %}