accounts/urls.py
from django.urls import path

app_name = 'accounts'

# accounts views
from accounts.views import SignupView
from accounts.views import UserLogout
from accounts.views import UserLoginView


urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', UserLogout.as_view(), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

# Static Files settings import 
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.views import serve
from django.conf import settings

# Apps Urls
from accounts import urls as accounts_urls
from authority import urls as authority_urls
from customer import urls as customer_urls
from home import urls as home_urls
from products import urls as products_urls
from payment import urls as payment_urls
from deleveryman import urls as deleveryman_urls
from reports import urls as report_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(accounts_urls)),
    path('', include(authority_urls)),
    path('', include(customer_urls)),
    path('', include(home_urls)),
    path('', include(products_urls)),
    path('', include(payment_urls)),
    path('', include(deleveryman_urls)),
    path('', include(report_urls)),

]

# Serve Static Files
# for serve static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, view=serve)

customer/urls.py
from django.urls import path


app_name = 'customer'

#Import Views
from customer.views import CustomerHomeView
from customer.views import MyOrderListView
from customer.views import MyConfirmedOrderListView
from customer.views import AddProfileInfo

urlpatterns = [

path('customer/', CustomerHomeView.as_view(), name='customer'),
path('my_pending_order/', MyOrderListView.as_view(), name='my_pending_list'),
path('my_confirmed_order/', MyConfirmedOrderListView.as_view(), name='my_confirmed_list'),
path('edit-profile/<int:pk>/', AddProfileInfo.as_view(),name="edit_profile")
    
]

home/urls.py
from django.urls import path

app_name='home'

# Home Views
from home.views import home
from home.views import manage_chart

urlpatterns = [
    path("", home.Home.as_view(), name="home"),
    path("home/", home.Home.as_view(), name="home"),
    path("all-product", home.AllProductView.as_view(), name="all_products"),
    path("product-details/<int:pk>/", home.ProductsDetailsView.as_view(), name="product_details"),
    
]


# manage order
urlpatterns += [
    path('add-to-cart/<int:pk>/', manage_chart.add_to_cart, name='add_to_cart'),
    path('cart-details/', manage_chart.ChartProductListView.as_view(), name='cart_details'),
    path('remove-from_cart/<int:pk>/', manage_chart.remove_form_cart, name='remove_form_cart'),
    path('increase-from-cart/<int:pk>/',manage_chart.increase_cart_item, name='increase_cart'),
    path('decrease-from-cart/<int:pk>/',manage_chart.decrease_cart_item, name='decrease_cart'),
    path('my-order/', manage_chart.MyOrderListView.as_view(),name="my_order"),
]

customer/models.py
from django.db import models

# Abstract Base Models
from common.models import BaseModel

# Import Models
from accounts.models import User

# Create your models here.

#Customer Billing Address
class BillingAddress(BaseModel):
    address_of = models.OneToOneField(User, on_delete=models.CASCADE, related_name='billing_user')
    address = models.CharField(max_length=200, blank=True, null=True)
    contact_number = models.CharField(max_length=20, blank=True)
    city = models.CharField(max_length=50,blank=True, null=True)
    country = models.CharField(max_length=50,blank=True, null=True, default='Bangladesh')
    post_code = models.CharField(max_length=50,blank=True, null=True)


# Customer Shipping Address
class ShippingAddress(BaseModel):
    address_of = models.OneToOneField(User, on_delete=models.CASCADE, related_name='shipping_user')
    receiver_name = models.CharField(max_length=100, blank=True, null=True)
    address = models.CharField(max_length=200, blank=True, null=True)
    contact_number = models.CharField(max_length=20, blank=True)
    city = models.CharField(max_length=50,blank=True, null=True)
    country = models.CharField(max_length=50,blank=True, null=True, default='Bangladesh')
    post_code = models.CharField(max_length=50,blank=True, null=True)

customer/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib import messages

# Import Generic View
from django.views.generic import TemplateView
from django.views.generic import ListView
from django.views.generic import UpdateView

# Permission Classes
from django.contrib.auth.mixins import LoginRequiredMixin
from customer.permissions import CustomerPassesTestMixin

# Import Models
from accounts.models import Profile
from accounts.forms import ProfileForm
from authority.models import ShippingCharge
from products.models import Order




# Create your views here.
class CustomerHomeView(LoginRequiredMixin,CustomerPassesTestMixin, TemplateView):
    template_name = 'customer/customer.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Customer Panel" 
        context["orders"] = Order.objects.filter(user=self.request.user, ordered=True).order_by('-id')[:10]
        context["pending_order"] = Order.objects.filter(user=self.request.user, ordered=True, order_confirm=False).count()
        context["confirmed_order"] = Order.objects.filter(user=self.request.user, ordered=True, order_confirm=True).count()
        context["total_orders"] = Order.objects.filter(user=self.request.user, ordered=True).count()
        return context
    

class MyOrderListView(LoginRequiredMixin, ListView):
    model = Order
    context_object_name = 'orders'
    template_name = 'customer/pending_order.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user, ordered=True, order_confirm=False).order_by('id')[:10]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "My order"
        context["shipping_charge"] = ShippingCharge.objects.latest('id')
        return context
    

class MyConfirmedOrderListView(LoginRequiredMixin, ListView):
    model = Order
    context_object_name = 'orders'
    template_name = 'customer/confirmed_order.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user, ordered=True, order_confirm=True).order_by('id')[:10]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "My order"
        context["shipping_charge"] = ShippingCharge.objects.latest('id')
        return context

class AddProfileInfo(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = 'customer/customer_profile.html'
    success_url = reverse_lazy('customer:customer')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Add/Edit Profile'
        return context
    
    def form_valid(self, form):
        messages.success(self.request, "Profile Updated Successfully")
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.warning(self.request, "Some thing Wron! Try agning")
        return super().form_invalid(form)

customer/templates/customer_base/customer_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title> {% block title %}{% endblock title %} </title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

     <!-- font-aswome cdn -->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
     <script src="https://kit.fontawesome.com/ddee993d4e.js" crossorigin="anonymous"></script>
</head>

<body>
    <div class="container-fluid position-relative bg-white d-flex p-0">
        {% comment %} <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End --> {% endcomment %}


        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-light navbar-light">
                <a href="{% url 'customer:customer' %}" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary"><i class="fa fa-hashtag me-2"></i>E-Shop</h3>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="{{request.user.profile.photo.url}}" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">{{request.user.profile.full_name}}</h6>
                        <span>Customer</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a href="index.html" class="nav-item nav-link"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa-solid fa-user"></i></i>My Orders</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="{% url 'customer:my_pending_list' %}" class="dropdown-item"><i class="fa-solid fa-user-plus me-2"></i>Pending Orders</a>
                            <a href="{% url 'customer:my_confirmed_list' %}" class="dropdown-item"><i class="fa-solid fa-user me-2"></i>Confirmed Orders</a>
                        </div>
                    </div>    
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->


        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
                <a href="{% static 'index.html' %}" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
               
                <div class="navbar-nav align-items-center ms-auto">
                    
                    {% comment %} <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-bell me-lg-2"></i>
                            <span class="d-none d-lg-inline-flex">Notificatin</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Profile updated</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">New user added</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Password changed</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item text-center">See all notifications</a>
                        </div>
                    </div> {% endcomment %}
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <img class="rounded-circle me-lg-2" src="{{request.user.profile.photo.url}}" alt="" style="width: 40px; height: 40px;">
                            <span class="d-none d-lg-inline-flex"> {{request.user.profile.full_name}} </span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="{% url 'customer:edit_profile' request.user.profile.id %}" class="dropdown-item">My Profile</a>
                            {% comment %} <a href="#" class="dropdown-item">Settings</a> {% endcomment %}
                            <a href="{% url 'accounts:logout' %}" class="dropdown-item">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->

             <!-- Messages Start -->
            {% if messages %}
            {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" {% endif %}>
                    <i class="fa fa-exclamation-circle me-2"></i>{{ message }}!
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            
            {% endfor %}
            {% endif %}

             <!-- Blank Start -->
             <div class="container-fluid pt-4 px-4">
                {% block body %}
                
                {% endblock body %}
            </div>
        



            <!-- Footer Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-light rounded-top p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                            &copy; <a href="#">Your Site Name</a>, All Right Reserved. 
                        </div>
                        <div class="col-12 col-sm-6 text-center text-sm-end">
                            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                            Designed By <a href="https://htmlcodex.com">HTML Codex</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -->
        </div>
        <!-- Content End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/chart/chart.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>